# Generated by Django 5.2.5 on 2025-08-26 06:15

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Debtor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "total_debt_amount",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("late_payments_count", models.PositiveIntegerField()),
                (
                    "monthly_income",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "employment_status",
                    models.CharField(
                        choices=[
                            ("EMPLOYED", "Employed"),
                            ("GOVERNMENT_EMPLOYED", "Government Employed"),
                            ("SELF_EMPLOYED", "Self Employed"),
                            ("RETIRED", "Retired"),
                            ("UNEMPLOYED", "Unemployed"),
                            ("STUDENT", "Student"),
                        ],
                        help_text="Employment status affects income stability assessment",
                        max_length=20,
                    ),
                ),
                (
                    "contract_type",
                    models.CharField(
                        choices=[
                            ("PERMANENT", "Permanent"),
                            ("CONTRACT", "Contract"),
                            ("TEMPORARY", "Temporary"),
                            ("FREELANCE", "Freelance"),
                        ],
                        default="PERMANENT",
                        max_length=20,
                    ),
                ),
                (
                    "industry_sector",
                    models.CharField(
                        choices=[
                            ("HEALTHCARE", "Healthcare"),
                            ("EDUCATION", "Education"),
                            ("GOVERNMENT", "Government"),
                            ("UTILITIES", "Utilities"),
                            ("INSURANCE", "Insurance"),
                            ("TECHNOLOGY", "Technology"),
                            ("FINANCE", "Finance"),
                            ("MANUFACTURING", "Manufacturing"),
                            ("PROFESSIONAL_SERVICES", "Professional Services"),
                            ("TELECOMMUNICATIONS", "Telecommunications"),
                            ("TRANSPORTATION", "Transportation"),
                            ("RETAIL", "Retail"),
                            ("HOSPITALITY", "Hospitality"),
                            ("CONSTRUCTION", "Construction"),
                            ("ENERGY", "Energy"),
                            ("ENTERTAINMENT", "Entertainment"),
                            ("REAL_ESTATE", "Real Estate"),
                        ],
                        help_text="Industry sector affects risk assessment",
                        max_length=30,
                    ),
                ),
                (
                    "family_situation",
                    models.CharField(
                        choices=[
                            ("MARRIED_DUAL_INCOME", "Married - Dual Income"),
                            ("MARRIED_SINGLE_INCOME", "Married - Single Income"),
                            ("SINGLE_NO_DEPENDENTS", "Single - No Dependents"),
                            ("UNMARRIED_LIVING_TOGETHER", "Unmarried Living Together"),
                            ("DIVORCED_NO_DEPENDENTS", "Divorced - No Dependents"),
                            ("SINGLE_WITH_DEPENDENTS", "Single - With Dependents"),
                            ("DIVORCED_WITH_DEPENDENTS", "Divorced - With Dependents"),
                            ("WIDOWED_WITH_DEPENDENTS", "Widowed - With Dependents"),
                        ],
                        help_text="Family situation affects financial stability assessment",
                        max_length=30,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Debtor",
                "verbose_name_plural": "Debtors",
            },
        ),
    ]
