# Generated by Django 5.2.5 on 2025-08-26 21:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("risk_service", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RiskScore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_score", models.FloatField()),
                ("risk_level", models.CharField(max_length=20)),
                ("factor_breakdown", models.JSONField()),
                ("calculated_at", models.DateTimeField(auto_now=True)),
                (
                    "debtor",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="risk_score",
                        to="risk_service.debtor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Risk Score",
                "verbose_name_plural": "Risk Scores",
            },
        ),
    ]
