# Generated by Django 5.2.5 on 2025-08-27 09:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("risk_service", "0002_riskscore"),
    ]

    operations = [
        migrations.AddField(
            model_name="debtor",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("UNPAID", "Unpaid"),
                    ("PARTIAL", "Partial"),
                    ("PAID", "Paid"),
                ],
                default="UNPAID",
                help_text="Current payment status of the debt",
                max_length=7,
            ),
        ),
    ]
