"""
Risk scoring constants and O(1) lookup maps.

Notes:
    - Provides categorical risk scores consumed by RiskScorer.
    - Split from code for maintainability and testing.
"""

from .choices import (
    CONTRACT_CONTRACT,
    CONTRACT_FREELANCE,
    # Contract
    CONTRACT_PERMANENT,
    CONTRACT_TEMPORARY,
    # Employment
    EMPLOYMENT_EMPLOYED,
    EMPLOYMENT_GOVERNMENT,
    EMPLOYMENT_RETIRED,
    EMPLOYMENT_SELF_EMPLOYED,
    EMPLOYMENT_STUDENT,
    EMPLOYMENT_UNEMPLOYED,
    FAMILY_DIVORCED_NO_DEPENDENTS,
    FAMILY_DIVORCED_WITH_DEPENDENTS,
    # Family
    FAMILY_MARRIED_DUAL_INCOME,
    FAMILY_MARRIED_SINGLE_INCOME,
    FAMILY_SINGLE_NO_DEPENDENTS,
    FAMILY_SINGLE_WITH_DEPENDENTS,
    FAMILY_UNMARRIED_LIVING_TOGETHER,
    FAMILY_WIDOWED_WITH_DEPENDENTS,
    INDUSTRY_CONSTRUCTION,
    INDUSTRY_EDUCATION,
    INDUSTRY_ENERGY,
    INDUSTRY_ENTERTAINMENT,
    INDUSTRY_FINANCE,
    # Industry
    INDUSTRY_GOVERNMENT,
    INDUSTRY_HEALTHCARE,
    INDUSTRY_HOSPITALITY,
    INDUSTRY_INSURANCE,
    INDUSTRY_MANUFACTURING,
    INDUSTRY_PROFESSIONAL_SERVICES,
    INDUSTRY_REAL_ESTATE,
    INDUSTRY_RETAIL,
    INDUSTRY_TECHNOLOGY,
    INDUSTRY_TELECOMMUNICATIONS,
    INDUSTRY_TRANSPORTATION,
    INDUSTRY_UTILITIES,
)

# Hash maps for O(1) categorical lookups
EMPLOYMENT_RISK_SCORES = {
    EMPLOYMENT_EMPLOYED: 2,
    EMPLOYMENT_GOVERNMENT: 1,
    EMPLOYMENT_SELF_EMPLOYED: 5,
    EMPLOYMENT_RETIRED: 4,
    EMPLOYMENT_UNEMPLOYED: 9,
    EMPLOYMENT_STUDENT: 7,
}

CONTRACT_RISK_SCORES = {
    CONTRACT_PERMANENT: 2,
    CONTRACT_CONTRACT: 5,
    CONTRACT_TEMPORARY: 7,
    CONTRACT_FREELANCE: 8,
}

INDUSTRY_RISK_SCORES = {
    # Low risk industries
    INDUSTRY_GOVERNMENT: 1,
    INDUSTRY_HEALTHCARE: 2,
    INDUSTRY_UTILITIES: 2,
    INDUSTRY_EDUCATION: 2,
    INDUSTRY_INSURANCE: 3,
    INDUSTRY_TECHNOLOGY: 3,
    # Medium risk
    INDUSTRY_FINANCE: 4,
    INDUSTRY_MANUFACTURING: 5,
    INDUSTRY_PROFESSIONAL_SERVICES: 4,
    INDUSTRY_TELECOMMUNICATIONS: 4,
    INDUSTRY_TRANSPORTATION: 5,
    # High risk
    INDUSTRY_RETAIL: 7,
    INDUSTRY_HOSPITALITY: 8,
    INDUSTRY_CONSTRUCTION: 8,
    INDUSTRY_ENERGY: 6,
    INDUSTRY_ENTERTAINMENT: 9,
    INDUSTRY_REAL_ESTATE: 7,
}

FAMILY_RISK_SCORES = {
    FAMILY_MARRIED_DUAL_INCOME: 1,
    FAMILY_MARRIED_SINGLE_INCOME: 3,
    FAMILY_SINGLE_NO_DEPENDENTS: 4,
    FAMILY_UNMARRIED_LIVING_TOGETHER: 5,
    FAMILY_DIVORCED_NO_DEPENDENTS: 5,
    FAMILY_SINGLE_WITH_DEPENDENTS: 8,
    FAMILY_DIVORCED_WITH_DEPENDENTS: 9,
    FAMILY_WIDOWED_WITH_DEPENDENTS: 9,
}
