# Generated by Django 5.2.5 on 2025-08-27 13:23

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PartnerSyncRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("debtor_id", models.IntegerField(unique=True)),
                (
                    "internal_balance",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "external_balance",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "internal_status",
                    models.CharField(
                        choices=[
                            ("UNPAID", "Unpaid"),
                            ("PARTIAL", "Partial Payment"),
                            ("PAID", "Fully Paid"),
                        ],
                        max_length=7,
                    ),
                ),
                (
                    "external_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("UNPAID", "Unpaid"),
                            ("PARTIAL", "Partial Payment"),
                            ("PAID", "Fully Paid"),
                        ],
                        max_length=7,
                        null=True,
                    ),
                ),
                (
                    "reconciliation_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending Sync"),
                            ("MATCHED", "Data Matched"),
                            ("DISCREPANCY", "Data Mismatch"),
                        ],
                        default="PENDING",
                        max_length=12,
                    ),
                ),
                ("synced_at", models.DateTimeField(auto_now=True)),
                ("partner_name", models.CharField(default="TruAccord", max_length=50)),
            ],
            options={
                "db_table": "partner_sync_records",
            },
        ),
    ]
